// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0

package sqlvods

import (
	"time"

	"github.com/google/uuid"
)

type Recording struct {
	ID           uuid.UUID
	FetchedAt    time.Time
	GzippedBytes []byte
	StreamsID    uuid.UUID
}

type Stream struct {
	ID                   uuid.UUID
	StreamerID           string
	StreamID             string
	StartTime            time.Time
	MaxViews             int64
	LastUpdatedAt        time.Time
	StreamerLoginAtStart string
}
