// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0

package sqlvods

import (
	"time"
)

type Recording struct {
	ID           string
	FetchedAt    time.Time
	GzippedBytes []byte
	StreamsID    string
}

type Stream struct {
	ID                   string
	StreamerID           string
	StreamID             string
	StartTime            time.Time
	MaxViews             int32
	LastUpdatedAt        time.Time
	StreamerLoginAtStart string
}
